/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProductRouteImport } from './routes/product'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhCNIndexRouteImport } from './routes/zh-CN/index'
import { Route as ZhCNSecurityRouteImport } from './routes/zh-CN/security'
import { Route as ZhCNProductRouteImport } from './routes/zh-CN/product'
import { Route as ZhCNDevelopersRouteImport } from './routes/zh-CN/developers'
import { Route as ZhCN404RouteImport } from './routes/zh-CN/404'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ZhCNDocsSplatRouteImport } from './routes/zh-CN/docs/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNIndexRoute = ZhCNIndexRouteImport.update({
  id: '/zh-CN/',
  path: '/zh-CN/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNSecurityRoute = ZhCNSecurityRouteImport.update({
  id: '/zh-CN/security',
  path: '/zh-CN/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNProductRoute = ZhCNProductRouteImport.update({
  id: '/zh-CN/product',
  path: '/zh-CN/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNDevelopersRoute = ZhCNDevelopersRouteImport.update({
  id: '/zh-CN/developers',
  path: '/zh-CN/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCN404Route = ZhCN404RouteImport.update({
  id: '/zh-CN/404',
  path: '/zh-CN/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhCNDocsSplatRoute = ZhCNDocsSplatRouteImport.update({
  id: '/zh-CN/docs/$',
  path: '/zh-CN/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/developers': typeof DevelopersRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/zh-CN/404': typeof ZhCN404Route
  '/zh-CN/developers': typeof ZhCNDevelopersRoute
  '/zh-CN/product': typeof ZhCNProductRoute
  '/zh-CN/security': typeof ZhCNSecurityRoute
  '/zh-CN/': typeof ZhCNIndexRoute
  '/zh-CN/docs/$': typeof ZhCNDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/developers': typeof DevelopersRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/zh-CN/404': typeof ZhCN404Route
  '/zh-CN/developers': typeof ZhCNDevelopersRoute
  '/zh-CN/product': typeof ZhCNProductRoute
  '/zh-CN/security': typeof ZhCNSecurityRoute
  '/zh-CN': typeof ZhCNIndexRoute
  '/zh-CN/docs/$': typeof ZhCNDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/developers': typeof DevelopersRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/zh-CN/404': typeof ZhCN404Route
  '/zh-CN/developers': typeof ZhCNDevelopersRoute
  '/zh-CN/product': typeof ZhCNProductRoute
  '/zh-CN/security': typeof ZhCNSecurityRoute
  '/zh-CN/': typeof ZhCNIndexRoute
  '/zh-CN/docs/$': typeof ZhCNDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/developers'
    | '/product'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/api/search'
    | '/docs/$'
    | '/zh-CN/404'
    | '/zh-CN/developers'
    | '/zh-CN/product'
    | '/zh-CN/security'
    | '/zh-CN/'
    | '/zh-CN/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/developers'
    | '/product'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/api/search'
    | '/docs/$'
    | '/zh-CN/404'
    | '/zh-CN/developers'
    | '/zh-CN/product'
    | '/zh-CN/security'
    | '/zh-CN'
    | '/zh-CN/docs/$'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/developers'
    | '/product'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/api/search'
    | '/docs/$'
    | '/zh-CN/404'
    | '/zh-CN/developers'
    | '/zh-CN/product'
    | '/zh-CN/security'
    | '/zh-CN/'
    | '/zh-CN/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DevelopersRoute: typeof DevelopersRoute
  ProductRoute: typeof ProductRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ZhCN404Route: typeof ZhCN404Route
  ZhCNDevelopersRoute: typeof ZhCNDevelopersRoute
  ZhCNProductRoute: typeof ZhCNProductRoute
  ZhCNSecurityRoute: typeof ZhCNSecurityRoute
  ZhCNIndexRoute: typeof ZhCNIndexRoute
  ZhCNDocsSplatRoute: typeof ZhCNDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/': {
      id: '/zh-CN/'
      path: '/zh-CN'
      fullPath: '/zh-CN/'
      preLoaderRoute: typeof ZhCNIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/security': {
      id: '/zh-CN/security'
      path: '/zh-CN/security'
      fullPath: '/zh-CN/security'
      preLoaderRoute: typeof ZhCNSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/product': {
      id: '/zh-CN/product'
      path: '/zh-CN/product'
      fullPath: '/zh-CN/product'
      preLoaderRoute: typeof ZhCNProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/developers': {
      id: '/zh-CN/developers'
      path: '/zh-CN/developers'
      fullPath: '/zh-CN/developers'
      preLoaderRoute: typeof ZhCNDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/404': {
      id: '/zh-CN/404'
      path: '/zh-CN/404'
      fullPath: '/zh-CN/404'
      preLoaderRoute: typeof ZhCN404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-CN/docs/$': {
      id: '/zh-CN/docs/$'
      path: '/zh-CN/docs/$'
      fullPath: '/zh-CN/docs/$'
      preLoaderRoute: typeof ZhCNDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DevelopersRoute: DevelopersRoute,
  ProductRoute: ProductRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ZhCN404Route: ZhCN404Route,
  ZhCNDevelopersRoute: ZhCNDevelopersRoute,
  ZhCNProductRoute: ZhCNProductRoute,
  ZhCNSecurityRoute: ZhCNSecurityRoute,
  ZhCNIndexRoute: ZhCNIndexRoute,
  ZhCNDocsSplatRoute: ZhCNDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
