import type {
  CodexPluginDetailView,
  CodexPluginListResult,
  CodexSkillListResult,
} from "../../../ipc/src/index.js"
import cloudflareLogo from "../assets/plugins/cloudflare.svg"
import figmaLogo from "../assets/plugins/figma.svg"
import githubLogo from "../assets/plugins/github.svg"
import gmailLogo from "../assets/plugins/gmail.svg"
import linearLogo from "../assets/plugins/linear.svg"
import notionLogo from "../assets/plugins/notion.svg"
export const pluginDemo: CodexPluginListResult = {
  errors: [],
  marketplaces: [
    {
      name: "OpenAI",
      path: null,
      plugins: [
        {
          availability: "AVAILABLE",
          brandColor: "#10a37f",
          capabilities: ["apps", "skills"],
          category: "Productivity",
          description: "Triage PRs, issues, CI, and publish flows",
          developerName: "OpenAI",
          displayName: "GitHub",
          enabled: true,
          featured: true,
          id: "github@openai-curated",
          installed: true,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "github",
          sourceType: "remote",
          version: "1.4.0",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#f97316",
          capabilities: ["skills"],
          category: "Infrastructure",
          description: "Cloud platform guidance and deployment workflows",
          developerName: "Cloudflare",
          displayName: "Cloudflare",
          enabled: false,
          featured: true,
          id: "cloudflare@openai-curated",
          installed: false,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "cloudflare",
          sourceType: "remote",
          version: "0.1.2",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#4285f4",
          capabilities: ["apps", "mcp"],
          category: "Communication",
          description: "Search, summarize, and draft work across Gmail",
          developerName: "Google",
          displayName: "Gmail",
          enabled: false,
          featured: false,
          id: "gmail@openai-curated",
          installed: false,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "gmail",
          sourceType: "remote",
          version: "1.0.0",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#111111",
          capabilities: ["apps", "mcp", "skills"],
          category: "Knowledge",
          description: "Find project context and keep workspace pages current",
          developerName: "Notion",
          displayName: "Notion",
          enabled: true,
          featured: false,
          id: "notion@openai-curated",
          installed: true,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "notion",
          sourceType: "remote",
          version: "1.1.0",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#5e6ad2",
          capabilities: ["apps", "mcp"],
          category: "Planning",
          description: "Triage issues, update projects, and summarize roadmaps",
          developerName: "Linear",
          displayName: "Linear",
          enabled: false,
          featured: false,
          id: "linear@openai-curated",
          installed: false,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "linear",
          sourceType: "remote",
          version: "1.0.3",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#f24e1e",
          capabilities: ["apps", "mcp", "skills"],
          category: "Design",
          description: "Bring design context and assets into implementation work",
          developerName: "Figma",
          displayName: "Figma",
          enabled: false,
          featured: false,
          id: "figma@openai-curated",
          installed: false,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "figma",
          sourceType: "remote",
          version: "1.2.0",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#2563eb",
          capabilities: ["skills"],
          category: "Security",
          description: "Review authorized repositories for plausible vulnerabilities",
          developerName: "OpenAI",
          displayName: "Codex Security",
          enabled: true,
          featured: false,
          id: "codex-security@openai-curated",
          installed: true,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "codex-security",
          sourceType: "remote",
          version: "1.0.0",
        },
        {
          availability: "AVAILABLE",
          brandColor: "#22c55e",
          capabilities: ["skills"],
          category: "Web3",
          description: "Reusable wallet and transaction analysis workflows for Cypheria",
          developerName: "Cypheria",
          displayName: "Web3 Operations",
          enabled: false,
          featured: false,
          id: "web3-operations@personal",
          installed: false,
          installPolicy: "AVAILABLE",
          logoUrl: null,
          marketplaceName: "OpenAI",
          marketplacePath: null,
          name: "web3-operations",
          sourceType: "local",
          version: "0.1.0",
        },
      ],
    },
  ],
}

export const skillDemo: CodexSkillListResult = {
  errors: [],
  skills: [
    {
      brandColor: "#14b8a6",
      cwd: "/Users/demo/cypheria",
      dependencyCount: 0,
      description: "Inspect wallet activity with a reusable personal workflow.",
      displayName: "Wallet Review",
      enabled: true,
      iconUrl: null,
      name: "wallet-review",
      path: "/Users/demo/.codex/skills/wallet-review/SKILL.md",
      pluginId: null,
      scope: "user",
    },
    {
      brandColor: "#64748b",
      cwd: "/Users/demo/cypheria",
      dependencyCount: 0,
      description: "Apply this repository’s release checklist.",
      displayName: "Release Checklist",
      enabled: true,
      iconUrl: null,
      name: "release-checklist",
      path: "/Users/demo/cypheria/.agents/skills/release-checklist/SKILL.md",
      pluginId: null,
      scope: "repo",
    },
    {
      brandColor: "#8b5cf6",
      cwd: "Cypheria",
      dependencyCount: 0,
      description: "Create or update reusable Codex skills.",
      displayName: "Skill Creator",
      enabled: true,
      iconUrl: null,
      name: "skill-creator",
      path: "/demo/skill-creator/SKILL.md",
      pluginId: null,
      scope: "system",
    },
    {
      brandColor: "#0ea5e9",
      cwd: "Cypheria",
      dependencyCount: 1,
      description: "Search and cite official OpenAI documentation.",
      displayName: "OpenAI Docs",
      enabled: true,
      iconUrl: null,
      name: "openai-docs",
      path: "/demo/openai-docs/SKILL.md",
      pluginId: null,
      scope: "system",
    },
  ],
}

const previewLogos: Record<string, string> = {
  github: githubLogo,
  cloudflare: cloudflareLogo,
  gmail: gmailLogo,
  notion: notionLogo,
  linear: linearLogo,
  figma: figmaLogo,
}
const publicMarket = pluginDemo.marketplaces[0]
if (publicMarket) {
  const localPlugins = publicMarket.plugins.filter((plugin) => plugin.sourceType === "local")
  publicMarket.plugins = publicMarket.plugins.filter((plugin) => plugin.sourceType !== "local")
  publicMarket.kinds = ["vertical"]
  for (const plugin of publicMarket.plugins) plugin.sourceKinds = ["vertical"]
  for (const plugin of localPlugins) {
    plugin.sourceKinds = ["local"]
    plugin.marketplaceName = "Local examples"
    plugin.marketplacePath = "/preview/marketplaces/examples"
  }
  pluginDemo.marketplaces.push({
    name: "Local examples",
    path: "/preview/marketplaces/examples",
    kinds: ["local"],
    plugins: localPlugins,
  })
}
for (const marketplace of pluginDemo.marketplaces) {
  for (const plugin of marketplace.plugins) plugin.logoUrl = previewLogos[plugin.name] ?? null
}

export const githubPreviewDetail: CodexPluginDetailView = {
  description:
    "Use GitHub to inspect repositories, review pull requests, address feedback, debug failing Actions checks, and prepare code changes for review through a connector-first workflow with targeted CLI fallbacks.",
  shareUrl: null,
  websiteUrl: "https://github.com",
  privacyPolicyUrl: null,
  termsOfServiceUrl: null,
  prompts: [
    "Explain this repo's authentication using code and docs: components, request flow, and how credentials and tokens are handled",
    "Summarize this pull request like a senior reviewer: what changed, what could break, and what tests are missing or weak",
    "Turn the last 7 days of commits and merged PRs into a stakeholder update: shipped work, risks, and next steps",
  ],
  apps: [
    {
      id: "github",
      name: "GitHub",
      description:
        "Access repositories, issues, and pull requests. Required for some features such as Codex",
      category: null,
      installUrl: null,
    },
    {
      id: "github-enterprise",
      name: "GitHub Enterprise",
      description: "Workspace-specific GitHub connector for a GitHub Enterprise host.",
      category: null,
      installUrl: null,
    },
  ],
  mcpServers: [],
  skills: [],
}
