/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WalletsRouteImport } from "./routes/wallets"
import { Route as PoliciesRouteImport } from "./routes/policies"
import { Route as PluginsRouteImport } from "./routes/plugins"
import { Route as NetworksRouteImport } from "./routes/networks"
import { Route as AutomationsRouteImport } from "./routes/automations"
import { Route as AuditRouteImport } from "./routes/audit"
import { Route as ApprovalsRouteImport } from "./routes/approvals"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SettingsModelsRouteImport } from "./routes/settings.models"
import { Route as SettingsAppearanceRouteImport } from "./routes/settings.appearance"
import { Route as SettingsAccountRouteImport } from "./routes/settings.account"

const WalletsRoute = WalletsRouteImport.update({
  id: "/wallets",
  path: "/wallets",
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: "/policies",
  path: "/policies",
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: "/plugins",
  path: "/plugins",
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: "/networks",
  path: "/networks",
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: "/approvals",
  path: "/approvals",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: "/settings/models",
  path: "/settings/models",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/settings/appearance",
  path: "/settings/appearance",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: "/settings/account",
  path: "/settings/account",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/approvals": typeof ApprovalsRoute
  "/audit": typeof AuditRoute
  "/automations": typeof AutomationsRoute
  "/networks": typeof NetworksRoute
  "/plugins": typeof PluginsRoute
  "/policies": typeof PoliciesRoute
  "/wallets": typeof WalletsRoute
  "/settings/account": typeof SettingsAccountRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/models": typeof SettingsModelsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/approvals": typeof ApprovalsRoute
  "/audit": typeof AuditRoute
  "/automations": typeof AutomationsRoute
  "/networks": typeof NetworksRoute
  "/plugins": typeof PluginsRoute
  "/policies": typeof PoliciesRoute
  "/wallets": typeof WalletsRoute
  "/settings/account": typeof SettingsAccountRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/models": typeof SettingsModelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/approvals": typeof ApprovalsRoute
  "/audit": typeof AuditRoute
  "/automations": typeof AutomationsRoute
  "/networks": typeof NetworksRoute
  "/plugins": typeof PluginsRoute
  "/policies": typeof PoliciesRoute
  "/wallets": typeof WalletsRoute
  "/settings/account": typeof SettingsAccountRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/models": typeof SettingsModelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/approvals"
    | "/audit"
    | "/automations"
    | "/networks"
    | "/plugins"
    | "/policies"
    | "/wallets"
    | "/settings/account"
    | "/settings/appearance"
    | "/settings/models"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/approvals"
    | "/audit"
    | "/automations"
    | "/networks"
    | "/plugins"
    | "/policies"
    | "/wallets"
    | "/settings/account"
    | "/settings/appearance"
    | "/settings/models"
  id:
    | "__root__"
    | "/"
    | "/approvals"
    | "/audit"
    | "/automations"
    | "/networks"
    | "/plugins"
    | "/policies"
    | "/wallets"
    | "/settings/account"
    | "/settings/appearance"
    | "/settings/models"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  AutomationsRoute: typeof AutomationsRoute
  NetworksRoute: typeof NetworksRoute
  PluginsRoute: typeof PluginsRoute
  PoliciesRoute: typeof PoliciesRoute
  WalletsRoute: typeof WalletsRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wallets": {
      id: "/wallets"
      path: "/wallets"
      fullPath: "/wallets"
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/policies": {
      id: "/policies"
      path: "/policies"
      fullPath: "/policies"
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/plugins": {
      id: "/plugins"
      path: "/plugins"
      fullPath: "/plugins"
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/networks": {
      id: "/networks"
      path: "/networks"
      fullPath: "/networks"
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/automations": {
      id: "/automations"
      path: "/automations"
      fullPath: "/automations"
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/audit": {
      id: "/audit"
      path: "/audit"
      fullPath: "/audit"
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/approvals": {
      id: "/approvals"
      path: "/approvals"
      fullPath: "/approvals"
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/models": {
      id: "/settings/models"
      path: "/settings/models"
      fullPath: "/settings/models"
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/appearance": {
      id: "/settings/appearance"
      path: "/settings/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/account": {
      id: "/settings/account"
      path: "/settings/account"
      fullPath: "/settings/account"
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  AutomationsRoute: AutomationsRoute,
  NetworksRoute: NetworksRoute,
  PluginsRoute: PluginsRoute,
  PoliciesRoute: PoliciesRoute,
  WalletsRoute: WalletsRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsModelsRoute: SettingsModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
