apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cypheria-relay-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cypheria-relay
      app.kubernetes.io/component: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cypheria-relay-worker
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cypheria-relay
      app.kubernetes.io/component: worker
