apiVersion: v1
kind: Service
metadata:
  name: cypheria-relay-worker
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: cypheria-relay
    app.kubernetes.io/component: worker
  ports:
    - name: internal
      port: 6771
      targetPort: internal
      protocol: TCP
